# Generated by Django 5.0 on 2024-01-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_post_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cast_and_crew',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='post',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
