# Generated by Django 5.0 on 2024-01-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_post_cast_and_crew_post_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
