# Generated by Django 5.0 on 2024-01-30 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_useraccount_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
    ]
