# Generated by Django 5.0 on 2024-02-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_post_location_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail',
            new_name='thumbnail_url',
        ),
    ]
